import { useEffect,useState } from 'react';
import Link from '@/lib/navigation';
import { apiFetch } from '@/lib/api';
import { categoryById } from '@/lib/categories';
import type { Stream } from '@/lib/types';
import { StreamCard } from './stream-card';
export function ChannelDirectory({categoryId}:{categoryId?:string}) {
  const category=categoryById(categoryId);
  const [streams,setStreams]=useState<Stream[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('recent'),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{void apiFetch<{streams:Stream[];hasMore:boolean}>(`/api/channels?limit=12&offset=${offset}&q=${encodeURIComponent(query)}&category=${encodeURIComponent(category?.name||'')}&status=${status}&sort=${sort}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted){setStreams(old=>offset?[...old,...d.streams.filter(s=>!old.some(o=>o.id===s.id))]:d.streams);setMore(d.hasMore);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);c.abort();};},[query,category?.name,status,sort,offset,retry]);
  function reset(){setOffset(0);setStreams([]);}
  return <><div className={`directory-heading ${category?`category-banner category-${category.id}`:''}`}><div>{category&&<Link className="breadcrumb" href="/categories">Categories / {category.name}</Link>}<p className="kicker">{category?'FIND YOUR KIND OF STREAM':'THE CHANNEL DIRECTORY'}</p><h1>{category?.label||'Every coin has a story.'}</h1><p>{category?.detail||'Find live channels, catch up with familiar faces and see who streamed last.'}</p></div>{category&&<strong aria-hidden="true">{category.code}</strong>}</div>
    <div className="directory-toolbar"><label className="directory-search"><span className="sr-only">Search channels</span><input value={query} maxLength={80} placeholder="Search by coin or channel…" onChange={e=>{setQuery(e.target.value);reset();}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);reset();}}><option value="all">Live & offline</option><option value="live">Live now</option><option value="offline">Offline</option></select></label><label>Sort by<select value={sort} onChange={e=>{setSort(e.target.value);reset();}}><option value="recent">Recently streamed</option><option value="viewers">Most viewers</option><option value="name">Coin name</option></select></label></div>
    {error?<div className="empty-state" role="alert"><h3>Could not load channels</h3><p>{error}</p><button className="soft-button" onClick={()=>setRetry(v=>v+1)}>Try again</button></div>:!streams.length&&loading?<div className="stream-skeletons" aria-label="Loading channels">{[1,2,3].map(n=><div key={n}/>)}</div>:!streams.length?<div className="empty-state"><h3>{query?'No matching channels':status==='live'?'No one is live here right now':'Room for a new community'}</h3><p>{query?'Try the coin’s name or symbol.':'When a creator sets up a channel, you can find it here, even between broadcasts.'}</p><Link className="primary-action" href="/go-live">Start a stream</Link></div>:<div className="stream-grid">{streams.map(s=><StreamCard key={s.id} stream={s}/>)}</div>}
    {more&&!error&&<button className="soft-button load-more" disabled={loading} onClick={()=>setOffset(v=>v+12)}>{loading?'Loading…':'Load more channels'}</button>}
  </>;
}
