import { useState,type FormEvent } from 'react';
import { toast } from 'sonner';
import Link from '@/lib/navigation';
import { useWallet } from '@/app/providers';
import { apiFetch } from '@/lib/api';
import { CATEGORIES,relativeTime } from '@/lib/categories';
import { useCreatorData,type CreatorChannel,type Credentials } from '@/lib/creator';
import { CreatorGate } from './creator-gate';
import { CoinAvatar } from './coin-avatar';
import { BroadcastCredentials } from './broadcast-credentials';
import { StudioManagement } from './studio-management';
import { BroadcastHistory } from './broadcast-history';
export function CreatorStudio() {
  const {token,wallet}=useWallet();
  return token?<StudioWorkspace key={wallet} token={token}/>:<CreatorGate/>;
}
function StudioWorkspace({token}:{token:string}) {
  const {markets,channels,loading,error,reload}=useCreatorData(token);
  const [selected,setSelected]=useState(''),[query,setQuery]=useState('');
  const market=markets.find(m=>m.id===selected)||markets[0];const channel=channels.find(c=>c.market_id===market?.id);
  return <><div className="page-title-row"><div><p className="kicker">YOUR CHANNELS, YOUR WAY</p><h1>Creator studio</h1><p>Make a home for every coin you create.</p></div><Link className="go-live-button" href={market?`/go-live/${encodeURIComponent(market.id)}`:'/go-live'}><span className="broadcast-dot"/>Go Live</Link></div>
    {error?<div className="empty-state" role="alert"><p>{error}</p><button className="soft-button" onClick={()=>void reload()}>Try again</button></div>:loading&&!markets.length?<div className="empty-state">Loading your studio…</div>:!markets.length?<div className="empty-state"><h2>Your channels start with your coins.</h2><p>No AQUA coins were found for this wallet. Connect the wallet that created your coin, or check again after it has synced.</p><button className="soft-button" onClick={()=>void reload()}>Check again</button></div>:<div className="studio-layout"><aside className="studio-coin-list"><div><h2>Your coins <span>{markets.length}</span></h2><input aria-label="Search creator coins" placeholder="Find a coin…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{markets.filter(m=>`${m.name} ${m.symbol}`.toLowerCase().includes(query.toLowerCase())).map(m=><button key={m.id} className={m.id===market?.id?'selected':''} onClick={()=>setSelected(m.id)}><CoinAvatar src={m.image_url} symbol={m.symbol}/><span><b>{m.symbol}</b><small>{m.name}</small></span>{m.stream_status==='live'&&<i className="nav-live-dot"/>}</button>)}<button className="studio-refresh" onClick={()=>void reload()} disabled={loading}>{loading?'Checking…':'Refresh coins'}</button></aside><div className="studio-workspace">
      {channel?<ChannelWorkspace key={channel.id} channel={channel} token={token} reload={reload}/>:<div className="new-channel"><CoinAvatar src={market?.image_url} symbol={market?.symbol||''} size="large"/><p className="kicker">{market?.name}</p><h2>Give {market?.symbol} a place to go live.</h2><p>Set your first title and category. We’ll prepare a channel and your private broadcast keys.</p><Link className="primary-action" href={`/go-live/${encodeURIComponent(market!.id)}`}>Set up this channel →</Link></div>}
    </div></div>}
  </>;
}
function ChannelWorkspace({channel,token,reload}:{channel:CreatorChannel;token:string;reload:()=>Promise<void>}) {
  const [tab,setTab]=useState('Overview'),[busy,setBusy]=useState(false),[title,setTitle]=useState(channel.title),[description,setDescription]=useState(channel.description),[category,setCategory]=useState(channel.category),[thumbnail,setThumbnail]=useState(channel.thumbnail_url||''),[announcement,setAnnouncement]=useState(''),[credentials,setCredentials]=useState<Credentials|null>(null),[error,setError]=useState('');
  const [scheduleTitle,setScheduleTitle]=useState(''),[scheduleDescription,setScheduleDescription]=useState(''),[scheduleAt,setScheduleAt]=useState(''),[duration,setDuration]=useState('60'),[revision,setRevision]=useState(0);
  async function act(fn:()=>Promise<void>,message?:string){setBusy(true);setError('');try{await fn();if(message)toast.success(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function save(e:FormEvent){e.preventDefault();await act(async()=>{await apiFetch(`/api/creator/streams/${channel.id}`,{method:'PATCH',body:JSON.stringify({title,description,category,thumbnailUrl:thumbnail.trim()||null})},token);await reload();},'Channel saved');}
  async function schedule(e:FormEvent){e.preventDefault();const when=new Date(scheduleAt).getTime();if(!Number.isFinite(when)||when<Date.now()+300000){setError('Choose a time at least five minutes from now.');return;}await act(async()=>{await apiFetch('/api/creator/schedules',{method:'POST',body:JSON.stringify({marketId:channel.market_id,streamId:channel.id,title:scheduleTitle,description:scheduleDescription,scheduledFor:when,durationMinutes:Number(duration)})},token);setScheduleTitle('');setScheduleDescription('');setScheduleAt('');setRevision(v=>v+1);},'Broadcast scheduled');}
  const live=channel.status==='live';
  return <><div className="studio-channel-heading"><CoinAvatar src={channel.image_url} symbol={channel.symbol} size="large"/><div><span className={`status-label ${live?'is-live':''}`}>{live?'● Live now':'Offline'}</span><h2>{channel.market_name}</h2><p>{channel.symbol} / {channel.slug}</p></div><Link className="soft-button" href={`/stream/${channel.slug}`}>View channel ↗</Link></div>
    <nav className="studio-tabs" aria-label="Channel settings">{['Overview','Stream details','Broadcast keys','Schedule','Moderation'].map(name=><button key={name} aria-current={tab===name?'page':undefined} className={tab===name?'active':''} onClick={()=>{setTab(name);setCredentials(null);setError('');}}>{name}</button>)}</nav>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="studio-tab-content" key={tab}>
    {tab==='Overview'&&<><div className="studio-overview"><div><span className="small-label">CURRENT BROADCAST</span><h3>{channel.title}</h3><p>{CATEGORIES.find(c=>c.name===channel.category)?.label||channel.category}</p><Link className="go-live-button" href={`/go-live/${encodeURIComponent(channel.market_id)}`}><span className="broadcast-dot"/>{live?'Manage broadcast':'Go Live'}</Link>{live&&<button className="danger-button" disabled={busy} onClick={()=>{if(window.confirm('End this broadcast? Viewers will see your channel as offline.'))void act(async()=>{await apiFetch(`/api/creator/streams/${channel.id}/end`,{method:'POST'},token);await reload();},'Broadcast ended');}}>End stream</button>}</div><dl><div><dt>Watching now</dt><dd>{live?channel.viewer_count:0}</dd></div><div><dt>Last broadcast</dt><dd>{channel.live_started_at?relativeTime(Number(channel.live_started_at)):'Not yet'}</dd></div></dl></div>{channel.last_error&&<p className="form-error">Broadcast issue: {channel.last_error}</p>}<form className="studio-form announcement-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await apiFetch(`/api/creator/streams/${channel.id}/announcement`,{method:'PUT',body:JSON.stringify({body:announcement})},token);setAnnouncement('');},'Announcement published');}}><div className="panel-heading"><h3>Say something to your community</h3><p>Pin an announcement below your stream.</p></div><label>Announcement<textarea rows={2} maxLength={280} required value={announcement} onChange={e=>setAnnouncement(e.target.value)} placeholder="Share an update, a link or what’s coming next."/></label><div className="form-actions"><button className="text-link" type="button" disabled={busy} onClick={()=>void act(async()=>{await apiFetch(`/api/creator/streams/${channel.id}/announcement`,{method:'DELETE'},token);},'Announcement removed')}>Remove current</button><button className="primary-action" disabled={busy||!announcement.trim()}>Publish</button></div></form><BroadcastHistory slug={channel.slug}/></>}
    {tab==='Stream details'&&<form className="studio-form" onSubmit={save}><div className="panel-heading"><h3>Make the channel yours.</h3><p>Set the details viewers see when they find your coin.</p></div><label>Stream title<input value={title} required minLength={3} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea rows={4} value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{!CATEGORIES.some(c=>c.name===category)&&<option>{category}</option>}{CATEGORIES.map(c=><option key={c.id} value={c.name}>{c.label} · {c.short}</option>)}</select></label><label>Channel cover URL <span className="optional">Optional</span><input type="url" maxLength={500} value={thumbnail} onChange={e=>setThumbnail(e.target.value)} placeholder="https://…"/><span className="field-hint">A public image URL. A wide 16:9 image works best.</span></label><div className="form-actions"><span>Changes apply to this coin only.</span><button className="primary-action" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form>}
    {tab==='Broadcast keys'&&<><div className="panel-heading"><h3>Connect your broadcasting software.</h3><p>Use OBS → Settings → Stream → Custom. Your keys stay the same between broadcasts.</p></div>{credentials?<BroadcastCredentials credentials={credentials}/>:<button className="primary-action" disabled={busy} onClick={()=>void act(async()=>{const d=await apiFetch<{credentials:Credentials}>(`/api/creator/streams/${channel.id}/credentials`,{},token);setCredentials(d.credentials);})}>{busy?'Loading…':'Reveal broadcast keys'}</button>}<div className="key-help"><h3>Need a new key?</h3><p>Resetting revokes the old key and disconnects an active broadcast. Update OBS with the replacement.</p><button className="danger-button" disabled={busy} onClick={()=>{if(window.confirm('Reset this stream key? The old key will stop working immediately.'))void act(async()=>{const d=await apiFetch<{credentials:Credentials}>(`/api/creator/streams/${channel.id}/rotate-key`,{method:'POST'},token);setCredentials(d.credentials);},'Stream key reset');}}>Reset stream key</button></div></>}
    {tab==='Schedule'&&<><form className="studio-form" onSubmit={schedule}><div className="panel-heading"><h3>Give your community a heads-up.</h3><p>Scheduled broadcasts appear on the public schedule.</p></div><label>Broadcast title<input required minLength={3} maxLength={100} value={scheduleTitle} onChange={e=>setScheduleTitle(e.target.value)} placeholder="What’s coming up?"/></label><label>Description<textarea rows={2} maxLength={500} value={scheduleDescription} onChange={e=>setScheduleDescription(e.target.value)}/></label><div className="form-columns"><label>When <span className="field-hint">Your local time</span><input required type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/></label><label>Length<select value={duration} onChange={e=>setDuration(e.target.value)}>{[30,60,90,120,180].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label></div><button className="primary-action" disabled={busy}>{busy?'Scheduling…':'Schedule broadcast'}</button></form><StudioManagement key={revision} streamId={channel.id} token={token} onRefresh={reload} view="schedule"/></>}
    {tab==='Moderation'&&<StudioManagement streamId={channel.id} token={token} onRefresh={reload} view="moderation"/>}
    </div>
  </>;
}
