import { useEffect,useRef,useState,type FormEvent } from 'react';
import Link,{useRouter} from '@/lib/navigation';
import { useWallet } from '@/app/providers';
import { apiFetch } from '@/lib/api';
import { CATEGORIES } from '@/lib/categories';
import { useCreatorData,type Credentials } from '@/lib/creator';
import { CreatorGate } from './creator-gate';
import { CoinAvatar } from './coin-avatar';
import { BroadcastCredentials } from './broadcast-credentials';
export function GoLive({marketId}:{marketId?:string}) {
  const {token,wallet}=useWallet();
  return token?<GoLiveWizard key={wallet} token={token} marketId={marketId}/>:<CreatorGate live/>;
}
function GoLiveWizard({token,marketId}:{token:string;marketId?:string}) {
  const {markets,channels,loading,error,reload}=useCreatorData(token),router=useRouter();
  const preparedIds=useRef<Record<string,string>>({});
  const [step,setStep]=useState(0),[selectedId,setSelectedId]=useState(marketId||''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Community'),[credentials,setCredentials]=useState<Credentials|null>(null),[channelId,setChannelId]=useState(''),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[query,setQuery]=useState('');
  const market=markets.find(m=>m.id===selectedId),channel=channels.find(c=>c.market_id===selectedId);
  useEffect(()=>{setChannelId(preparedIds.current[selectedId]||channel?.id||'');setTitle(channel?.title||'');setDescription(channel?.description||'');setCategory(channel?.category||'Community');setCredentials(null);},[selectedId,channel?.id]);
  async function prepare(e:FormEvent){e.preventDefault();if(!market)return;setBusy(true);setActionError('');
    try {let id=channelId;if(id)await apiFetch(`/api/creator/streams/${id}`,{method:'PATCH',body:JSON.stringify({title,description,category})},token);else{const result=await apiFetch<{stream:{id:string}}>('/api/creator/streams',{method:'POST',body:JSON.stringify({marketId:market.id,title,description,category})},token);id=result.stream.id;preparedIds.current[market.id]=id;setChannelId(id);}
      await apiFetch(`/api/creator/streams/${id}/enable`,{method:'POST'},token);
      const result=await apiFetch<{credentials:Credentials}>(`/api/creator/streams/${id}/credentials`,{},token);setCredentials(result.credentials);setStep(2);
    }catch(e){setActionError((e as Error).message);}finally{setBusy(false);}
  }
  async function start(){if(!channelId)return;setBusy(true);setActionError('');try{const result=await apiFetch<{slug:string;status:string}>(`/api/creator/streams/${channelId}/start`,{method:'POST'},token);setCredentials(null);router.push(`/stream/${result.slug}`);}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  return <div className="live-setup"><div className="page-title-row"><div><p className="kicker">YOUR COMMUNITY IS ONE STREAM AWAY</p><h1>Let’s go live.</h1></div><Link className="text-link" href="/studio">Back to studio</Link></div><ol className="setup-steps" aria-label="Broadcast setup">{['Choose your coin','Stream details','Connect & go live'].map((label,i)=><li key={label} className={step===i?'current':step>i?'complete':''} aria-current={step===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span>{label}</li>)}</ol>
    <div className="setup-layout"><section className="setup-panel" key={step}>
      {step===0&&<><div className="panel-heading"><h2>Who are you streaming with?</h2><p>Choose a coin created by your connected wallet.</p></div>{loading?<p className="inline-empty">Loading your coins…</p>:error?<div role="alert" className="inline-empty"><p>{error}</p><button className="soft-button" onClick={()=>void reload()}>Try again</button></div>:!markets.length?<div className="inline-empty"><h3>No creator coins found</h3><p>Use the wallet that launched your coin on AQUA. New coins can take a few minutes to appear.</p><button className="soft-button" onClick={()=>void reload()}>Check again</button></div>:<><input className="coin-search" aria-label="Search your coins" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find your coin…"/><div className="coin-picker">{markets.filter(m=>`${m.name} ${m.symbol}`.toLowerCase().includes(query.toLowerCase())).map(m=><button className={m.id===selectedId?'selected':''} key={m.id} onClick={()=>{setSelectedId(m.id);setActionError('');}} aria-pressed={m.id===selectedId}><CoinAvatar symbol={m.symbol} src={m.image_url}/><span><b>{m.name}</b><small>{m.symbol} · {m.stream_status==='live'?'Live now':m.stream_id?'Channel ready':'New channel'}</small></span><span className="selection-circle"/></button>)}</div>{!markets.some(m=>`${m.name} ${m.symbol}`.toLowerCase().includes(query.toLowerCase()))&&<p className="field-hint">No coins match your search.</p>}<div className="form-actions"><span>{market?`${market.symbol} selected`:'Choose a coin to continue'}</span><button className="primary-action" disabled={!market} onClick={()=>setStep(1)}>Continue →</button></div></>}</>}
      {step===1&&<form onSubmit={prepare} className="studio-form"><div className="panel-heading"><h2>Give them a reason to tune in.</h2><p>Your stream details appear in browse and on your channel.</p></div><label>Stream title<input autoFocus required minLength={3} maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What’s happening today?"/><span className="field-hint">{title.length}/100</span></label><label>Description<textarea rows={3} maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell your community what you’ll be talking about."/></label><fieldset className="category-choices"><legend>Category</legend>{CATEGORIES.map(c=><label key={c.id} className={category===c.name?'selected':''}><input type="radio" name="category" value={c.name} checked={category===c.name} onChange={()=>setCategory(c.name)}/><span><b>{c.label}</b><small>{c.short}</small></span></label>)}</fieldset>{actionError&&<p role="alert" className="form-error">{actionError}</p>}<div className="form-actions"><button type="button" className="text-link" disabled={busy} onClick={()=>setStep(0)}>← Change coin</button><button className="primary-action" disabled={busy||title.trim().length<3}>{busy?'Preparing channel…':'Get broadcast keys →'}</button></div></form>}
      {step===2&&credentials&&<><div className="panel-heading"><h2>Your stream is ready for OBS.</h2><p>In OBS, open Settings → Stream, choose Custom, then paste these two values.</p></div><BroadcastCredentials credentials={credentials}/><div className="obs-instructions"><span>ALMOST THERE</span><h3>Start streaming in OBS.</h3><p>Then press Go Live below to open your channel. Your stream appears in Browse as soon as Cloudflare receives your video.</p><small>Recommended: H.264 video, AAC audio, 2-second keyframes.</small></div>{actionError&&<p role="alert" className="form-error">{actionError}</p>}<div className="form-actions"><button className="text-link" disabled={busy} onClick={()=>{setStep(1);setCredentials(null);}}>← Edit details</button><button className="go-live-button large" disabled={busy} onClick={()=>void start()}><span className="broadcast-dot"/>{busy?'Opening channel…':'Go Live'}</button></div></>}
    </section><aside className="setup-preview"><p className="small-label">YOUR CHANNEL</p><div className={`preview-cover category-${CATEGORIES.find(c=>c.name===category)?.id||'community'}`}><span>{market?.symbol||'YOUR COIN'}</span><div className="cover-rings"/></div><div className="preview-details"><CoinAvatar symbol={market?.symbol||'SS'} src={market?.image_url}/><div><b>{title||'Your next great stream'}</b><p>{market?.name||'Choose a coin to get started'}</p></div></div><span className="preview-category">{CATEGORIES.find(c=>c.name===category)?.label||category}</span><div className="setup-note"><h3>A channel that stays yours.</h3><p>Your followers, chat and broadcast history stay together between streams.</p></div></aside></div>
  </div>;
}
