"use client";
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Radio, Users, Video } from 'lucide-react';
import { apiFetch, ApiError } from '@/lib/api';
import type { Stream } from '@/lib/types';
import { useWallet } from '@/app/providers';
import { ChatPanel } from './chat-panel';
import { FollowButton } from './follow-button';
import { ViewerPing } from './viewer-ping';
import { ReportDialog } from './report-dialog';
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(value);
function Chart({stream}:{stream:Stream}) {
  const points=stream.chart ?? []; const values=points.map(p=>p.priceUsd);const min=Math.min(...values),max=Math.max(...values),spread=max-min;
  const path=points.map((p,i)=>`${i?'L':'M'} ${i/Math.max(points.length-1,1)*600} ${spread?110-(p.priceUsd-min)/spread*90:65}`).join(' ');
  return <div className="market-chart"><div className="chart-heading"><div><small>Cached market price</small><b>{stream.market.priceUsd.toLocaleString('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:5})}</b></div><span className={stream.market.change24h>=0?'positive':'negative'}>{stream.market.change24h>0?'+':''}{stream.market.change24h.toFixed(2)}% / 24h</span></div>{points.length>=2 ? <><svg viewBox="0 0 600 132" role="img" aria-label="Price history from cached AQUA snapshots"><path d={path} fill="none" stroke="#1686c4" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><p className="wallet-note">{new Date(Number(points[0].time)).toLocaleString()} – {new Date(Number(points.at(-1)!.time)).toLocaleString()}</p></> : <p className="chart-empty">Price history appears after two market snapshots.</p>}</div>;
}
export function StreamRoom({slug}:{slug:string}) {
  const {token}=useWallet(); const [stream,setStream]=useState<Stream|null>(null); const [error,setError]=useState(''); const [missing,setMissing]=useState(false); const [retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setStream(null);setMissing(false);const load=async()=>{try{const result=await apiFetch<Stream>('/api/streams/'+encodeURIComponent(slug),{},token);if(active){setStream(result);setError('');}}catch(e){if(active){setError((e as Error).message);setMissing(e instanceof ApiError&&e.status===404);}}};void load();const timer=setInterval(()=>void load(),15000);return()=>{active=false;clearInterval(timer);};},[slug,token,retry]);
  if(!stream)return <main className="simple-page"><div className="empty-state"><h1>{missing?'Channel not found':error?'Could not load this stream':'Loading stream…'}</h1>{error&&<p>{error}</p>}{!missing&&error&&<button className="soft-button" onClick={()=>setRetry(v=>v+1)}>Try again</button>}<Link href="/">Back to Explore</Link></div></main>;
  return <main className="watch-page">{stream.status==='live'&&<ViewerPing streamId={stream.id}/>}<div className="watch-topbar"><Link href="/"><ArrowLeft size={17}/>Explore</Link><span>{stream.status==='live'?'Live':stream.status==='errored'?'Broadcast interrupted':'Offline'}</span></div>{error&&<p role="status" className="schedule-empty">Updates paused: {error}</p>}
    <div className="watch-grid"><section className="player-column"><div className="video-player">{stream.status==='live'&&stream.provider==='cloudflare'&&stream.playerUrl ? <iframe src={stream.playerUrl} title={stream.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/> : <div className="offline-player"><Video size={32}/><h2>{stream.status==='errored'?'The broadcast was interrupted':'This channel is offline'}</h2><p>Follow {stream.market.symbol} or check the schedule for the next stream.</p><Link href="/schedule">View schedule</Link></div>}{stream.status==='live'&&<><span className="live-chip">LIVE</span><span className="viewer-chip"><Users size={14}/>{stream.viewerCount}</span></>}</div><div className="stream-info-row"><div className="coin-row"><span className="coin-dot">{stream.market.symbol.slice(0,1)}</span><div><strong>{stream.market.symbol}</strong><small>{stream.market.name}</small></div></div><div className="stream-title"><h1>{stream.title}</h1><p>{stream.category}</p></div><FollowButton marketId={stream.market.id} initial={stream.followed}/></div>{stream.announcement&&<div className="stream-announcement"><Radio size={17}/><div><b>Creator announcement</b><p>{stream.announcement}</p></div></div>}</section><ChatPanel streamId={stream.id} initialMessages={[]}/></div>
    <div className="below-stream-grid"><section className="market-panel"><div className="market-panel-heading"><h2>{stream.market.symbol}</h2><a href={stream.market.aquaUrl} target="_blank" rel="noreferrer">View on AQUA<ArrowUpRight size={16}/></a></div><Chart stream={stream}/><div className="market-metrics"><span><small>Market cap</small><b>{money(stream.market.marketCapUsd)}</b></span><span><small>24h volume</small><b>{money(stream.market.volume24hUsd)}</b></span><span><small>Holders</small><b>{stream.market.holderCount.toLocaleString()}</b></span><span><small>Reward mode</small><b>{stream.market.rewardMode.replaceAll('_',' ')}</b></span></div><p className="wallet-note" style={{marginTop:16}}>Market figures are cached from AQUA and refresh approximately every five minutes. They are not a live trade feed.</p></section></div>
    <section className="stream-about"><h2>About this channel</h2><p>{stream.description||'The creator has not added a description yet.'}</p><div><span>{stream.followerCount??0} followers</span><ReportDialog streamId={stream.id}/></div></section>
  </main>;
}
