"use client";
import { useCallback,useEffect,useState } from 'react';
import { toast } from 'sonner';
import { apiFetch } from '@/lib/api';
interface Management {moderators:Array<{wallet:string}>;bans:Array<{wallet:string;reason:string;expires_at:number|null}>;schedules:Array<{id:string;title:string;scheduled_for:number}>;reports:Array<{id:string;reason:string;details:string;reported_wallet:string|null}>;}
export function StudioManagement({streamId,token,onRefresh}:{streamId:string;token:string;onRefresh:()=>Promise<void>}) {
 const [data,setData]=useState<Management|null>(null);const [error,setError]=useState('');const [wallet,setWallet]=useState('');const [reason,setReason]=useState('');const [minutes,setMinutes]=useState('60');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setData(await apiFetch<Management>(`/api/creator/streams/${streamId}/management`,{},token));setError('');}catch(e){setError((e as Error).message);}},[streamId,token]);
 useEffect(()=>{setData(null);void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[load]);
 async function act(path:string,method:string,body?:object){setBusy(true);try{await apiFetch(path,{method,...(body?{body:JSON.stringify(body)}:{})},token);toast.success('Saved');await load();await onRefresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 const prefix=`/api/moderation/streams/${streamId}`;
 return <div className="studio-grid" style={{marginTop:16}}><section className="studio-card"><h2>Broadcast controls</h2><p className="empty-copy">After ending a stream here, stop OBS, then enable the input before your next broadcast.</p><button className="soft-button" disabled={busy} onClick={()=>void act(`/api/creator/streams/${streamId}/enable`,'POST')}>Enable broadcast input</button><p style={{marginTop:16}}><button className="soft-button" disabled={busy} onClick={()=>void act(`/api/creator/streams/${streamId}/announcement`,'DELETE')}>Remove announcement</button></p><h3>Upcoming broadcasts</h3>{data?.schedules.length===0&&<p className="empty-copy">No upcoming broadcasts.</p>}{data?.schedules.map(item=><p key={item.id}>{item.title}<br/><small>{new Date(Number(item.scheduled_for)).toLocaleString()}</small> <button className="chat-retry" disabled={busy} onClick={()=>{if(window.confirm('Cancel this scheduled broadcast?'))void act(`/api/creator/schedules/${item.id}`,'DELETE');}}>Cancel</button></p>)}</section>
 <section className="studio-card"><h2>Chat moderation</h2>{error&&<p role="alert">{error}<button className="chat-retry" onClick={()=>void load()}>Retry</button></p>}<label>Solana wallet<input value={wallet} onChange={e=>setWallet(e.target.value.trim())} placeholder="Wallet address" maxLength={44}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={200}/></label><label>Timeout<select value={minutes} onChange={e=>setMinutes(e.target.value)}><option value="10">10 minutes</option><option value="60">1 hour</option><option value="1440">24 hours</option><option value="">Permanent ban</option></select></label><div className="inline-actions"><button disabled={busy||!wallet} onClick={()=>void act(prefix+'/bans/'+encodeURIComponent(wallet),'PUT',{reason,minutes:minutes?Number(minutes):null})}>Restrict chat</button><button disabled={busy||!wallet} onClick={()=>void act(prefix+'/moderators','POST',{wallet})}>Add moderator</button></div><h3 style={{marginTop:20}}>Moderators</h3>{data?.moderators.map(item=><p key={item.wallet} style={{overflowWrap:'anywhere',fontSize:14}}>{item.wallet}<button className="chat-retry" disabled={busy} onClick={()=>void act(prefix+'/moderators/'+encodeURIComponent(item.wallet),'DELETE')}>Remove</button></p>)}{data?.moderators.length===0&&<p className="empty-copy">No moderators added.</p>}<h3>Restricted wallets</h3>{data?.bans.map(item=><p key={item.wallet} style={{overflowWrap:'anywhere',fontSize:14}}>{item.wallet}<br/><small>{item.reason||'No reason provided'} · {item.expires_at?new Date(Number(item.expires_at)).toLocaleString():'Permanent'}</small><button className="chat-retry" disabled={busy} onClick={()=>void act(prefix+'/bans/'+encodeURIComponent(item.wallet),'DELETE')}>Unban</button></p>)}{data?.bans.length===0&&<p className="empty-copy">No active restrictions.</p>}</section>
 <section className="studio-card"><h2>Open reports</h2>{data?.reports.length===0&&<p className="empty-copy">No open reports for this channel.</p>}{data?.reports.map(report=><article key={report.id}><b>{report.reason.replaceAll('_',' ')}</b><p>{report.details||'No additional details.'}</p>{report.reported_wallet&&<p style={{overflowWrap:'anywhere'}}>{report.reported_wallet}</p>}<button className="soft-button" disabled={busy} onClick={()=>void act(prefix+'/reports/'+report.id,'PATCH',{status:'resolved'})}>Mark reviewed</button></article>)}</section></div>;
}
